#!/usr/bin/env bash
# =============================================================================
# Vendor kpack's release manifest into template/components/kpack.
# =============================================================================
# kpack publishes one release-<version>.yaml per GitHub release. It is
# committed here, pinned, with its sha256, so a customer's gitops repo never
# depends on a URL at sync time.
#
# TO BUMP KPACK:
#   1. change KPACK_VERSION below (https://github.com/buildpacks-community/kpack/releases)
#   2. run this script
#   3. run `make verify`
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

KPACK_VERSION="${KPACK_VERSION:-0.18.0}"
url="https://github.com/buildpacks-community/kpack/releases/download/v${KPACK_VERSION}/release-${KPACK_VERSION}.yaml"
out="template/components/kpack/release.yaml"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "fetching $url"
curl -fsSL "$url" -o "$work/release.yaml"
sum="$(shasum -a 256 "$work/release.yaml" | awk '{print $1}')"

{
  printf '# GENERATED by scripts/vendor-kpack.sh — do not edit.\n'
  printf '# kpack v%s (release asset release-%s.yaml).\n' "$KPACK_VERSION" "$KPACK_VERSION"
  printf '# source: %s\n' "$url"
  printf '# sha256 (upstream bytes): %s\n' "$sum"
  cat "$work/release.yaml"
} > "$out"

echo "wrote $out ($(grep -c '^kind:' "$out") objects, sha256 $sum)"
