#!/usr/bin/env bash
# =============================================================================
# Vendor Argo CD's upstream install manifests into template/components/argocd.
# =============================================================================
# The operator runs a kustomize build of components/argocd on a fresh
# management cluster, before anything can reach the network on Argo CD's
# behalf, and the customer's gitops repo must be buildable offline and
# reproducibly. So the upstream install.yaml is committed here, pinned, with its
# sha256 recorded, instead of being named by URL in the kustomization.
#
# TO BUMP ARGO CD:
#   1. change ARGOCD_VERSION below (latest stable v3.x from
#      https://github.com/argoproj/argo-cd/releases)
#   2. run this script
#   3. run `make verify`
#   4. one pull request, then cut a template version (see README)
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

ARGOCD_VERSION="${ARGOCD_VERSION:-v3.5.3}"
url="https://raw.githubusercontent.com/argoproj/argo-cd/${ARGOCD_VERSION}/manifests/install.yaml"
out="template/components/argocd/install.yaml"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "fetching $url"
curl -fsSL "$url" -o "$work/install.yaml"
sum="$(shasum -a 256 "$work/install.yaml" | awk '{print $1}')"

{
  printf '# GENERATED by scripts/vendor-argocd.sh — do not edit.\n'
  printf '# Argo CD %s full install (upstream manifests/install.yaml, UI included).\n' "$ARGOCD_VERSION"
  printf '# source: %s\n' "$url"
  printf '# sha256 (upstream bytes): %s\n' "$sum"
  cat "$work/install.yaml"
} > "$out"

echo "wrote $out ($(grep -c '^kind:' "$out") objects, sha256 $sum)"
